### ISSUE TITLE
bunch of warnings on Chandra.Maneuver 3.7.2

### ISSUE THREAD

**Issue by jeanconn** [sot/ska_helpers#7]
Not sure if this is a ska_helpers issue or a bug in the Chandra.Maneuver changes but I'm getting this mess of user warnings in the test root environment I installed in /proj/sot/ska3/test-2020.1 .

In [1]: import Chandra.Maneuver
/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/ska_helpers/version.py:85: UserWarning: Traceback (most recent call last):
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/ska_helpers/version.py", line 41, in get_version
    dist_info = get_distribution(distribution or package)
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 562, in get_distribution
    dist = get_provider(dist)
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 981, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 867, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Ska' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/ska_helpers/version.py", line 78, in get_version
    version = get_version(root=Path(*roots), relative_to=module.__file__)
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

  warnings.warn(traceback.format_exc() + '\n\n')
/proj/sot/ska3/test-2020.1/lib/python3.6/site-packages/ska_helpers/version.py:86: UserWarning: Failed to find a package version, setting to 0.0.0
  warnings.warn('Failed to find a package version, setting to 0.0.0')

**Comment by jeanconn** [comment]
I think this is an issue with `Ska.Sun` that is propagating to warnings on import of `Chandra.Maneuver`.

**Comment by jeanconn** [comment]
Looks like I get the same warning on Ska.astro and Ska.arc5gl which are the other two that have file structure like Ska/Sun.py instead of Ska/Sun/Sun.py .

**Comment by javierggt** [comment]
I fixed the issue on those packages, merged, tagged, and updated the corresponding skare3 issues.

The bottomline is that, when calling ska_helpers.get_version, we should do:
```
ska_helpers.get_version(__name__)
```
and not
```
ska_helpers.get_version(__package__)
```
